version: '3.8'

services:
  db:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME:-dba}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD:-secretsecret}
      - POSTGRES_DB=${DATASOURCE_DB_NAME:-hellojpa-db}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    image: 'brunoe/sample-hellojpa:latest'
    build: .
    depends_on:
      - db
    environment:
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-dba}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-secretsecret}
      - DATASOURCE_URL=${DATASOURCE_URL:-jdbc:postgresql://db/hellojpa-db}

volumes:
  pg-data:

