version: '3.8'

services:
  db:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_USER=${DB_USERNAME:-dba}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secretsecret}
      - POSTGRES_DB=${DB_NAME:-hellojpa-db}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    image: 'brunoe/sample-hellojpa:latest'
    build: .
    depends_on:
      - db
    environment:
      - DB_USERNAME=${DB_USERNAME:-dba}
      - DB_PASSWORD=${DB_PASSWORD:-secretsecret}
      - DB_URL=${DB_URL:-jdbc:postgresql://db/hellojpa-db}

volumes:
  pg-data:

