DROP SCHEMA IF  EXISTS EX_ENTITY;
DROP SCHEMA IF  EXISTS EX_MANY_TO_MANY;
DROP SCHEMA IF  EXISTS EX_ONE_TO_MANY_A;
DROP SCHEMA IF  EXISTS EX_ONE_TO_MANY_B;
DROP SCHEMA IF  EXISTS EX_BIOGRAPHY;
DROP SCHEMA IF  EXISTS EX_HOOK;
DROP SCHEMA IF  EXISTS EX_EMBEDDED_ID;
DROP SCHEMA IF  EXISTS EX_IDCLASS;