CREATE SCHEMA IF NOT EXISTS EX_ENTITY;
CREATE SCHEMA IF NOT EXISTS EX_MANY_TO_MANY;
CREATE SCHEMA IF NOT EXISTS EX_ONE_TO_MANY_A;
CREATE SCHEMA IF NOT EXISTS EX_ONE_TO_MANY_B;
CREATE SCHEMA IF NOT EXISTS EX_BIOGRAPHY;
CREATE SCHEMA IF NOT EXISTS EX_HOOK;